---
title: "Highrises with 10 or more fire inspection violations in Ward 1"
author: "Jessica Im"
date: format(Sys.time(), "%d %B %Y")
format: html
abstract: "My abstract."
bibliography: bibliography.bib
---

```{r}
#### Preamble ####
# Purpose:
# Author: Jessica Im
# Email: jessica.im@mail.utoronto.ca
# Date: 21 January 2024
```

```{r}
library(opendatatoronto)
library(dplyr)
library(tidyverse)
library(knitr)
library(janitor)
library(lubridate)
```


```{r}
highrise_fire_inspection_data <-
  read_csv(
    "unedited_fire_inspection_data.csv",
    show_col_types = FALSE
  )
```


```{r}
#### Clean ####
# Clean names and filter out highrises without a violation
highrise_fire_inspection_clean <-
  clean_names(highrise_fire_inspection_data)|>
  drop_na(violation_fire_code)
  
head(highrise_fire_inspection_clean)
```


```{r}
# Fix ward numbers so they are consistent
highrise_fire_inspection_clean <-
  highrise_fire_inspection_clean |>
  mutate(
    property_ward =
      case_match(
        property_ward,
        "01" ~ "1",
        "02" ~ "2",
        "03" ~ "3",
        "04" ~ "4",
        "05" ~ "5",
        "06" ~ "6",
        "07" ~ "7",
        "08" ~ "8",
        "09" ~ "9"
      )
  )
head(highrise_fire_inspection_clean)
```

```{r}
# Create a number of violations variable
highrise_fire_inspection_clean <-
  highrise_fire_inspection_clean |>
  group_by(property_address) |>
  mutate(number_of_violations = n())

highrise_fire_inspection_clean

```

```{r}
# Only select the columns of importance
highrise_fire_inspection_clean <-
  highrise_fire_inspection_clean |>
  select(property_address,
         property_ward,
         violation_fire_code,
         violation_description,
         number_of_violations)
head(highrise_fire_inspection_clean)
```



```{r}
write_csv(
  x = highrise_fire_inspection_clean,
  file = "highrise_fire_inspection.csv"
)

```

### Exploring my data
```{r}

#### Explore ####
highrise_fire_inspection_clean <-
  read_csv(
    "highrise_fire_inspection.csv",
    show_col_types = FALSE
  )

highrise_fire_inspection_clean |>
  ggplot(aes(x = property_ward)) +
  geom_bar() +
  theme_minimal() +
  labs(x = "Address", y = "Number of Violations") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```

# References
```{r}
write_bib()
```

